server:
  port: 8087
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE  #lb stands for load balance
          predicates:
            - Path=/microservices/user/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE  #lb stands for load balance
          predicates:
            - Path=/microservices/hotel/**,/microservices/staff/**
            
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE  #lb stands for load balance
          predicates:
            - Path=/microservices/rating/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
        defaultZone: http://localhost:8761/eureka

# Okta Security configuration
okta:
  oauth2:
    issuer: https://dev-90272233.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa7zgjoegXjkLqhK5d7
    client-secret: _Zoj85x4vu2kRywuFk9XxtzlxkIB9FLqP4hGRGS0
    scopes: openid, profile, email, offline_access