server:
  port: 8084
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE  #lb stands for load balance
          predicates:
            - Path=/microservices/user/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE  #lb stands for load balance
          predicates:
            - Path=/microservices/hotel/**
            
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE  #lb stands for load balance
          predicates:
            - Path=/microservices/rating/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
        defaultZone: http://localhost:8761/eureka